# Generated by Django 4.2.7 on 2026-04-28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("voice_reports", "0006_add_ai_trace"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voicereport",
            name="chart_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("line", "Line Chart"),
                    ("line_multi", "Multi-Line Chart"),
                    ("bar", "Bar Chart"),
                    ("bar_grouped", "Grouped Bar Chart"),
                    ("bar_stacked", "Stacked Bar Chart"),
                    ("pie", "Pie Chart"),
                    ("area", "Area Chart"),
                    ("map", "Map"),
                    ("combo_line_bar", "Combo Line/Bar Chart"),
                    ("card", "Card"),
                    ("table", "Table"),
                    ("scatter", "Scatter Plot"),
                    ("histogram", "Histogram"),
                    ("kpi", "Legacy KPI"),
                    ("number", "Legacy Number/KPI"),
                    ("scalar", "Legacy Scalar"),
                    ("grouped_bar", "Legacy Grouped Bar"),
                    ("stacked_bar", "Legacy Stacked Bar"),
                    ("combo", "Legacy Combo"),
                ],
                max_length=20,
            ),
        ),
    ]
