"""
Django settings for Small Whisper Backend (STATELESS AI WORKER).

⚠️ ARCHITECTURAL RULE: This backend is COMPLETELY STATELESS
- NO user authentication
- NO JWT validation
- NO user database
- NO permissions
- NO Django REST Framework (to avoid implicit auth)

This backend is a pure AI worker that:
1. Receives audio files
2. Transcribes using Whisper
3. Generates intent + SQL using LLM
4. Returns JSON data

ALL authentication and user management is handled by Main BI Backend (port 8000).

Generated by 'django-admin startproject' using Django 5.2.7.
"""

import os
from pathlib import Path
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "").strip()

# SECURITY WARNING: don't run with debug turned on in production!
_raw_debug = os.getenv("DJANGO_DEBUG", os.getenv("DEBUG", "false"))
DEBUG = str(_raw_debug).strip().lower() in {"1", "true", "yes", "on"}
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = "dev-only-ai-service-secret-key"
    else:
        raise ImproperlyConfigured("DJANGO_SECRET_KEY must be set when DEBUG is false.")

_raw_allowed_hosts = os.getenv("DJANGO_ALLOWED_HOSTS", os.getenv("ALLOWED_HOSTS", ""))
if _raw_allowed_hosts.strip():
    ALLOWED_HOSTS = [host.strip() for host in _raw_allowed_hosts.split(",") if host.strip()]
elif DEBUG:
    ALLOWED_HOSTS = ["localhost", "127.0.0.1"]
else:
    ALLOWED_HOSTS = []


# Application definition

STATELESS_MODE = str(os.getenv("AI_SERVICE_STATELESS_MODE", "true")).strip().lower() in {
    "1",
    "true",
    "yes",
    "on",
}

INSTALLED_APPS = [
    "corsheaders",
    "django.contrib.contenttypes",
    "django.contrib.staticfiles",
    "whisper_app",
    "reasoning_app",
    "llm_app",
]
if not STATELESS_MODE:
    INSTALLED_APPS = [
        "django.contrib.admin",
        "django.contrib.auth",
        "django.contrib.sessions",
        "django.contrib.messages",
        *INSTALLED_APPS,
    ]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    'corsheaders.middleware.CorsMiddleware',
]
if not STATELESS_MODE:
    MIDDLEWARE.insert(1, "django.contrib.sessions.middleware.SessionMiddleware")
    MIDDLEWARE.insert(
        MIDDLEWARE.index("django.middleware.clickjacking.XFrameOptionsMiddleware"),
        "django.contrib.auth.middleware.AuthenticationMiddleware",
    )
    MIDDLEWARE.insert(
        MIDDLEWARE.index("django.middleware.clickjacking.XFrameOptionsMiddleware"),
        "django.contrib.messages.middleware.MessageMiddleware",
    )
CORS_ALLOW_ALL_ORIGINS = False
_raw_cors_allowed_origins = os.getenv("DJANGO_CORS_ALLOWED_ORIGINS", "")
CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in _raw_cors_allowed_origins.split(",")
    if origin.strip()
]
if DEBUG and not CORS_ALLOWED_ORIGINS:
    CORS_ALLOWED_ORIGINS = [
        "http://localhost:3000",
        "http://127.0.0.1:3000",
    ]

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if STATELESS_MODE and not DEBUG:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.dummy",
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": os.getenv("AI_SERVICE_DB_ENGINE", "django.db.backends.sqlite3"),
            "NAME": os.getenv("AI_SERVICE_DB_NAME", str(BASE_DIR / "db.sqlite3")),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = []
if not STATELESS_MODE:
    AUTH_PASSWORD_VALIDATORS = [
        {
            "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
        },
        {
            "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        },
        {
            "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
        },
        {
            "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
        },
    ]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Service-to-service authentication validation
INTERNAL_API_TOKEN = str(
    os.getenv("INTERNAL_API_TOKEN", "")
    or os.getenv("INTERNAL_SERVICE_TOKEN", "")
    or os.getenv("QUERY_SERVICE_INTERNAL_TOKEN", "")
    or os.getenv("SERVICE_INTERNAL_TOKEN", "")
    or ""
).strip()
SERVICE_INTERNAL_TOKEN = INTERNAL_API_TOKEN
if not INTERNAL_API_TOKEN:
    import logging
    logger = logging.getLogger(__name__)
    logger.warning(
        "SERVICE_INTERNAL_TOKEN not configured. "
        "Service-to-service calls to query-service will fail. "
        "Set SERVICE_INTERNAL_TOKEN environment variable."
    )

_raw_csrf_trusted_origins = os.getenv("DJANGO_CSRF_TRUSTED_ORIGINS", "")
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in _raw_csrf_trusted_origins.split(",")
    if origin.strip()
]
if DEBUG and not CSRF_TRUSTED_ORIGINS:
    CSRF_TRUSTED_ORIGINS = [
        "http://localhost:3000",
        "http://127.0.0.1:3000",
    ]
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,

    "formatters": {
        "simple": {
            "format": "[{levelname}] {asctime} {name}: {message}",
            "style": "{",
        },
    },

    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
    },

    "loggers": {
        "pipeline": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "reasoning_app": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}
