PENDING = "PENDING"
QUEUED = "QUEUED"
TRANSCRIBING = "TRANSCRIBING"
AI_PROCESSING = "AI_PROCESSING"
SQL_GENERATED = "SQL_GENERATED"
EXECUTING_QUERY = "EXECUTING_QUERY"
VISUALIZING = "VISUALIZING"
COMPLETED = "COMPLETED"
FAILED = "FAILED"
PARTIAL = "PARTIAL"

TERMINAL_STATUSES = {COMPLETED, FAILED, PARTIAL}
ACTIVE_STATUSES = {QUEUED, TRANSCRIBING, AI_PROCESSING, SQL_GENERATED, EXECUTING_QUERY, VISUALIZING}
